### ISSUE TITLE
Scripts(*.sh, configure-devel...) are not in executable mode

### ISSUE THREAD

**Issue by ganli2015** [kunpengcompute/hucx#6]
![image](https://user-images.githubusercontent.com/10879733/94091947-1d412680-fe4c-11ea-9d59-6ba686420567.png)
![image](https://user-images.githubusercontent.com/10879733/94091955-2500cb00-fe4c-11ea-8513-3ea88373a000.png)
The scripts above(autogen.sh, configure-devel, configure-opt...) are not in executable mode by default and we cannot compile directly.

**Comment by nsosnsos** [comment]
I have noticed this problem and it will be fixed soon.
